# LinearRegression_BostonHausingData

<h2>必要モジュールとデータのインポート</h2>

In [65]:
#各種モジュールの読み込み
from sklearn.datasets import load_boston
from pandas import DataFrame
import numpy as np
from sklearn.model_selection import train_test_split

In [66]:
# ボストンデータを格納
boston = load_boston()

### データフレームの作成

In [67]:
#　説明変数をdfへ格納
df = DataFrame(data=boston.data, columns = boston.feature_names)

In [68]:
# 上から5件を表示
df.head(5)

CRIM    ZN  INDUS  CHAS    NOX  ...  RAD    TAX  PTRATIO       B  LSTAT
0  0.00632  18.0   2.31   0.0  0.538  ...  1.0  296.0     15.3  396.90   4.98
1  0.02731   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  396.90   9.14
2  0.02729   0.0   7.07   0.0  0.469  ...  2.0  242.0     17.8  392.83   4.03
3  0.03237   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  394.63   2.94
4  0.06905   0.0   2.18   0.0  0.458  ...  3.0  222.0     18.7  396.90   5.33

[5 rows x 13 columns]

In [69]:
# 目的変数をdfへ追加
df['PRICE'] = np.array(boston.target)

In [70]:
# 上から5件を表示
df.head(5)

CRIM    ZN  INDUS  CHAS    NOX  ...    TAX  PTRATIO       B  LSTAT  PRICE
0  0.00632  18.0   2.31   0.0  0.538  ...  296.0     15.3  396.90   4.98   24.0
1  0.02731   0.0   7.07   0.0  0.469  ...  242.0     17.8  396.90   9.14   21.6
2  0.02729   0.0   7.07   0.0  0.469  ...  242.0     17.8  392.83   4.03   34.7
3  0.03237   0.0   2.18   0.0  0.458  ...  222.0     18.7  394.63   2.94   33.4
4  0.06905   0.0   2.18   0.0  0.458  ...  222.0     18.7  396.90   5.33   36.2

[5 rows x 14 columns]

### 線形回帰分析(CRIM)

In [71]:
#カラムを指定してデータを表示
df[['CRIM']].head(5)

CRIM
0  0.00632
1  0.02731
2  0.02729
3  0.03237
4  0.06905

In [72]:
#説明変数
X = df.loc[:, ['CRIM']].values

In [74]:
#Xリストの表示(1-5)
X[0:5]

array([[0.00632],
       [0.02731],
       [0.02729],
       [0.03237],
       [0.06905]])

In [76]:
#目的変数
y = df.loc[:, ['PRICE']].values

In [77]:
#yリストの表示(1-5)
y[0:5]

array([[24. ],
       [21.6],
       [34.7],
       [33.4],
       [36.2]])

In [78]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [79]:
#LinearRegressionをインポート
from sklearn.linear_model import LinearRegression

In [80]:
#オブジェクを生成
model = LinearRegression()
#model.get_params()
#model = LinearRegression(fit_intercept = True, normalize = False, copy_x = True, n_jobs = 1)

In [81]:
#fit関数でモデルを適合
model.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [82]:
#予測
model.score(X_test, y_test)

0.13929075575345728

In [92]:
#指定して予測
model.predict([[0.3]])

array([[23.6419528]])

<h2>重回帰分析(2変数)</h2>

In [84]:
#カラムを指定してデータを表示
df[['CRIM', 'RM']].head(5)

CRIM     RM
0  0.00632  6.575
1  0.02731  6.421
2  0.02729  7.185
3  0.03237  6.998
4  0.06905  7.147

In [85]:
#説明変数
X2 = df.loc[:, ['CRIM', 'RM']].values

In [86]:
#目的変数
y2 = df.loc[:, 'PRICE'].values

In [88]:
X2_train, X2_test, y2_train, y2_test = train_test_split(X2, y2, random_state=1)

In [89]:
#オブジェクト生成
model2 = LinearRegression()

In [91]:
#fit関数でモデルを適合
model2.fit(X2_train, y2_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [94]:
#予測
model2.score(X2_test, y2_test)

0.6403553865176794

In [95]:
#指定して予測
model2.predict([[0.3, 4]])

array([5.65671804])