# PYTorch基礎

## 1.Tensor(テンソル)

### (1) Tensorの生成と変換



```
# ライブラリをインポート
import torch
```

```
# データ型を指定してテンソルを作成
data = [1, 2, 3]
ts_data = torch.tensor(data,dtype=torch.float64)
```


```
# 0から9の1次元テンソルの生成
ts_x = torch.arange(0, 10)
# テンソルをndarrayに変換
np_x = ts_x.numpy()  
```

```
# 0から9の1次元ndarrayの生成
np_x = np.arange(0, 10)
# ndarrayをテンソルに変換
ts_x = torch.from_numpy(np_x)
```






In [ ]:
# ライブラリの読み込み
import torch
import numpy as np

np_y = np.ones([5,3])

# テンソル化
ts_y = torch.tensor(np_y)

# Q1
print(ts_y)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


### (2)Tensorの操作

```
# テンソルのサイズを確認
ts.size()
```

```
# 単一の値（=スカラー値）を取り出す
ts[0][0].item()
```




In [ ]:
# ライブラリの読み込み
import torch

data = [[[1, 2, 3],[4, 5, 6]],[[7, 8, 9],[10, 11, 12]]]

# テンソル化
ts_data = torch.tensor(data)

# Q1
print(ts_data.size())

torch.Size([2, 2, 3])


### (3)Tensorの演算処理【四則演算】

演算処理を行う時の注意

```
1. 四則演算はTensor同士かTensorとPythonのスカラーの数値との間でのみ可能であること
2. Tensor同士の演算処理は同じ型である必要があること
```


```
# 四則演算
data*10
data１*data2
```





In [ ]:
# ライブラリの読み込み
import torch

ts_data = torch.tensor([[1, 2, 3],[4, 5, 6]])
ts_data1 = torch.tensor([[10, 20, 30],[40, 50, 60]]) 

# テンソル同士の引き算
ts_x = ts_data - ts_data1

# Q1
print(ts_x)

tensor([[ -9, -18, -27],
        [-36, -45, -54]])


### (4)Tensorの演算処理【数学関数】



```
torch.abs()	#絶対値
torch.mean()	#平均値
torch.std()	#標準偏差
```



```
# 次元の変更 2×3→3×2
data.view(3, 2)
```

```
# 1次元に変更する
data.view(-1)
```




In [ ]:
# ライブラリのインポート
import torch

# テンソルの生成
ts_sample = torch.tensor([[1,2,3],[-4,-5,-6]],dtype=float)

# Q1
print(torch.abs(ts_sample))

# Q2
print(torch.std(ts_sample))

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
tensor(3.9370, dtype=torch.float64)


### (5)GPUの利用



```
# PU使用可能環境であるかの確認
import torch
print(torch.cuda.is_available())
```

```
#計算デバイスを使い分ける(下記の関数の引数)
CPUのみしか計算デバイスがない場合は、device = 'CPU'
GPU1台目に計算をさせたい場合は、device = 'cuda:0'
GPU2台を並列で計算をさせたい場合は、device = 'cuda:0' もしくは、device = 'cuda:1' を使い分け
```

```
# GPU1台目にテンソルの計算をさせる例
torch.tensor([[1, 2], [3, 4.]], device="cuda:0")
```







## 2.Autograd(自動微分)

### (1)自動微分の基本的概念

【回帰問題や分類問題を解く流れ】

```
1.予測器となる関数をモデル化（DNN、CNN、RNN、etc...）
2.予測結果を評価するための損失関数を定義（BCE、MSE、CE、etc...）
3.勾配法によって損失を最小化
    ・ 勾配を計算（backpropagation）
    ・ パラメータを更新（SGD、Adamなど）
```



### (2)自動微分の実施新しいセクション



```
# 自動微分を可能にする(requires_grad=True)
data = torch.tensor(1.0, requires_grad=True ,dtype=float)
```
勾配計算

```
# テンソルをrequires_grad=Trueで生成
x = torch.tensor(2.0, requires_grad=True,dtype=float)
# 計算グラフを定義
y = x ** 3
# 勾配を計算
y.backward()
# 勾配を表示
print(x.grad)
```
勾配計算(三角関数)
```
# テンソルをrequires_grad=Trueで生成
x = torch.tensor(np.pi, requires_grad=True,dtype=float)
# 計算グラフを定義
y = torch.sin(x)
# 勾配を計算
y.backward()
# 勾配を表示
print(x.grad)
```
勾配計算(偏微分)


```
# テンソルをrequires_grad=Trueで生成
x = torch.tensor(1.0, requires_grad=True,dtype=float)
y = torch.tensor(2.0, requires_grad=True,dtype=float)
# 計算グラフを定義
z = (x + 5 * y) ** 2
# 勾配を計算
z.backward()
# 勾配を表示
print(x.grad)
print(y.grad)
```







In [ ]:
# ライブラリの読み込み
import torch

# テンソルをrequires_grad=Trueで生成
x = torch.tensor(1.0, requires_grad=True, dtype=float)
y = torch.tensor(2.0, requires_grad=True, dtype=float)

# 計算グラフを定義
z = (5 * x + y) ** 3

# 勾配を計算
z.backward()

# yの勾配を表示
print(y.grad)

tensor(147., dtype=torch.float64)


## 3.ニューラルネットの作成(IrisNet)

### (1)データセットについて

Irisデータの読み込み
```
import pandas as pd
from sklearn.datasets import load_iris
iris = load_iris()
df_iris = pd.DataFrame(iris.data, columns=iris.feature_names)
df_iris['target'] = iris.target
df_iris.loc[df_iris['target'] == 0, 'target'] = "setosa"
df_iris.loc[df_iris['target'] == 1, 'target'] = "versicolor"
df_iris.loc[df_iris['target'] == 2, 'target'] = "virginica"
```
**Irisのデータセット詳細**
```
全データ:150行、5列
sepal length (cm):がく片の長さ
sepal width (cm):幅の長さ
petal length (cm):花弁の長さ
petal width (cm):幅の長さ
target:花の種類（setosa,versicolor,virginica）
```





In [ ]:
# ライブラリのインポート
import pandas as pd
from sklearn.datasets import load_iris

# データのロード
iris = load_iris()
df_iris = pd.DataFrame(iris.data, columns=iris.feature_names)

# 花の種類（target）のカラムを作成
df_iris['target'] = iris.target
df_iris.loc[df_iris['target'] == 0, 'target'] = "setosa"
df_iris.loc[df_iris['target'] == 1, 'target'] = "versicolor"
df_iris.loc[df_iris['target'] == 2, 'target'] = "virginica"

df_iris

sepal length (cm)  sepal width (cm)  ...  petal width (cm)     target
0                  5.1               3.5  ...               0.2     setosa
1                  4.9               3.0  ...               0.2     setosa
2                  4.7               3.2  ...               0.2     setosa
3                  4.6               3.1  ...               0.2     setosa
4                  5.0               3.6  ...               0.2     setosa
..                 ...               ...  ...               ...        ...
145                6.7               3.0  ...               2.3  virginica
146                6.3               2.5  ...               1.9  virginica
147                6.5               3.0  ...               2.0  virginica
148                6.2               3.4  ...               2.3  virginica
149                5.9               3.0  ...               1.8  virginica

[150 rows x 5 columns]

### (2)ネットワークの定義1


**【ネットワーク詳細】**
```
input:4種
隠れ層1のノード:12個
隠れ層2のノード:8個
output:3種
```
**【上記のネットワークのプログラム】**
```
#0
import torch.nn as nn
import torch.nn.functional as F

#1
class Net(nn.Module):
    #2
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(4, 12)
        self.fc2 = nn.Linear(12, 8)
        self.fc3 = nn.Linear(8, 3)

    #3
    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x
```





In [ ]:
#0
import torch.nn as nn
import torch.nn.functional as F

#1
class Net(nn.Module):
    #2
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(4, 12)
        self.fc2 = nn.Linear(12, 8)
        self.fc3 = nn.Linear(8, 3)

    #3
    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

### (3)ネットワークの定義2

**【PyTorchを使ったニューラルネットの定義方法】**
```
1.ライブラリのインポート
2.classとしてネットワークを作成
3.init関数の定義
4.forward関数の定義
```
**【1.ライブラリのインポート】**
```
torch.nn.Moduleがすべてのニューラルネットワークモジュールの基本クラス
torch.nn.functionalがニューラルネットワーク構成のための関数群
```
**【2.classとしてネットワークを作成】**
```
ネットワークをクラスとして設計し、そのクラス内でinit関数の定義とforward関数の定義の2種類を定義
モデルのクラス作成時には、nn.Moduleを継承することでnn.Module内のメソッドも使うことが可能
```
**【3.init関数の定義】**
```
IrisNetのinit関数にhello iris1と表示するプログラムと、クラス内の変数testに文字列hello iris2を格納
```
**【4.forward関数の定義】**
```
線形結合はnn.Linearで表現され、nn.Linear(4,12)と書けば、4次元の入力を受け取り、12次元の出力を得る
```





In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

#1
class IrisNet(nn.Module):

    #2
    def __init__(self):
        super(IrisNet, self).__init__()
        self.fc1 = nn.Linear(4, 12)
        self.fc2 = nn.Linear(12, 8)
        self.fc3 = nn.Linear(8, 4)
        self.fc4 = nn.Linear(4, 3)


    #3
    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = F.relu(self.fc3(x))
        x = self.fc4(x)
        return x

# モデルのインスタンス作成
net = IrisNet()

# サンプルデータ（torch.tensor([[5.1000, 3.5000, 1.4000, 0.2000]])）を入力し、アウトプット確認
print(net(torch.tensor([[5.1000, 3.5000, 1.4000, 0.2000]])))


tensor([[ 0.0530, -0.0682, -0.0506]], grad_fn=<AddmmBackward>)


### (4)ネットワークの学習準備【交差検証】

**【学習準備】**
```
1.データの検証法選定
2.最適化手法選定
3.loss関数の選定
```
**【1.データの検証法選定(今回は交差検証)】**
```
1. データを分割
2. 一部のデータを使って学習
3. 残ったデータで分析手法の精度を評価する
4. 一部のデータの分け方を変化させ、２と３を繰り返す
5. 複数回行ったテスト結果をもとに、分析手法の精度を評価する
```
**【K-分割交差検証 実装】**
```
from sklearn.model_selection import KFold

kf = KFold(n_splits=3,shuffle=True,random_state=1993)
for fold,(train_index, test_index) in enumerate(kf.split(iris.data, iris.target)):
    print("Fold：{}".format(fold),"len(train_index)：{}".format(len(train_index)), "len(test_index)：{}".format(len(test_index)))
```

**【K-分割交差検証 引数】**
```
引数n_split: データの分割数、デフォルトは3
引数shuffle: 連続する数字のグループ分けとするか（True もしくはFalse）
引数random_state: 乱数の設定
```








In [ ]:
# ライブラリのインポート
import pandas as pd
from sklearn.model_selection import KFold
from sklearn.datasets import load_iris

# アイリスのデータのロード
iris = load_iris()
df_iris = pd.DataFrame(iris.data, columns=iris.feature_names)
df_iris['target'] = iris.target
df_iris.loc[df_iris['target'] == 0, 'target'] = "setosa"
df_iris.loc[df_iris['target'] == 1, 'target'] = "versicolor"
df_iris.loc[df_iris['target'] == 2, 'target'] = "virginica"

# 交差検証（fold=3）
kf = KFold(n_splits=3,shuffle=True,random_state=1993)
for fold,(train_index, test_index) in enumerate(kf.split(iris.data, iris.target)):
    print("Fold：{}".format(fold),"len(train_index)：{}".format(len(train_index)), "len(test_index)：{}".format(len(test_index)))

Fold：0 len(train_index)：100 len(test_index)：50
Fold：1 len(train_index)：100 len(test_index)：50
Fold：2 len(train_index)：100 len(test_index)：50


### (5)ネットワークの学習準備【最適化手法選定】

**【確率的勾配降下法(SGD)】**
```
ライブンラリのインポート
import torch.optim as optim
```
**【確率的勾配降下法(SGD) 引数】**
```
引数params: 最適化するパラメーター
引数lr: 学習率（float）
引数momentum: モーメンタム（float）
引数dampening: モーメンタムの勢い（float）
引数weight_decay: L2ノルムの強さ（float）
引数nesterov: momentumをモーメンタムとして適用するか
```

```
# optimizerの勾配の初期化を行う
optimizer.zero_grad()
# ネットワークのパラメータの更新
optimizer.step()
# 学習率を0.01
optimizer = optim.SGD(net.parameters(), lr=0.01)
```




In [ ]:
# ライブラリのインポート
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

#1
class IrisNet(nn.Module):
    #2
    def __init__(self):
        super(IrisNet, self).__init__()
        self.fc1 = nn.Linear(4, 12)
        self.fc2 = nn.Linear(12, 8)
        self.fc3 = nn.Linear(8, 4)
        self.fc4 = nn.Linear(4, 3)
    #3
    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = F.relu(self.fc3(x))
        x = self.fc4(x)
        return x

# モデルのインスタンス作成
net = IrisNet()

# optimizerの設定
optimizer = optim.SGD(net.parameters(), lr=0.01)

### (6)ネットワークの学習準備【loss関数選定】

**代表的な損失関数**

```
1.平均二乗和誤差(Mean Squared Error: MSE)
  回帰分析のように連続的な値をとるときには最もオーソドックスなMSEを用います
2.交差エントロピー誤差(CrossEntropy: CE)
  分類問題のような元々決まっているラベルに対して推測を行う際にはCEを用います
```



**交差エントロピー誤差 実装**

```
import torch.nn as nn
criterion = nn.CrossEntropyLoss()
```



### (7)ニューラルネットワークの学習1

**定数定義**


```
FOLD = 3
IS_SHUFFLE = True
SEED = 1234
EPOCH = 10
LEARNING_LATE = 0.01
```



**データの準備**


```
#  アイリスデータロード
iris = datasets.load_iris()

X_train = iris.data
y_train = iris.target
x = torch.tensor(X_train,dtype = torch.float)
y = torch.tensor(y_train)
net = IrisNet()
```



**学習**


```
for i in range(EPOCH):
    # 勾配初期化
    optimizer.zero_grad()
    output = net(x)

    # loss算出
    loss = criterion(output, y)
    loss.backward()
    optimizer.step()
    print('epoch: {},'.format(i) + 'loss: {:.10f}'.format(loss))
```



In [1]:
# ライブラリのインポート
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np
from sklearn import datasets

# ネットワークの定義
class IrisNet(nn.Module):

    def __init__(self):
        super(IrisNet, self).__init__()
        self.fc1 = nn.Linear(4, 12)
        self.fc2 = nn.Linear(12, 8)
        self.fc3 = nn.Linear(8, 3)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    
#  定数定義
FOLD = 3
IS_SHUFFLE = True
SEED = 1234
EPOCH = 10
LEARNING_LATE = 0.01

#  アイリスデータロード
iris = datasets.load_iris()

X_train = iris.data
y_train = iris.target
x = torch.tensor(X_train,dtype = torch.float)
y = torch.tensor(y_train)
net = IrisNet()

# optimezer定義
optimizer = optim.SGD(net.parameters(), lr=LEARNING_LATE)

# loss関数定義
criterion = nn.CrossEntropyLoss()

for i in range(EPOCH):
    # 勾配初期化
    optimizer.zero_grad()
    output = net(x)

    # loss算出
    loss = criterion(output, y)
    loss.backward()
    optimizer.step()
    print('epoch: {},'.format(i) + 'loss: {:.10f}'.format(loss))

epoch: 0,loss: 1.1565742493
epoch: 1,loss: 1.1507802010
epoch: 2,loss: 1.1454604864
epoch: 3,loss: 1.1405483484
epoch: 4,loss: 1.1360044479
epoch: 5,loss: 1.1317890882
epoch: 6,loss: 1.1278642416
epoch: 7,loss: 1.1241998672
epoch: 8,loss: 1.1207684278
epoch: 9,loss: 1.1175469160


### (8)ニューラルネットワークの学習2

**交差検証**


```
for fold,(train_index, test_index) in enumerate(kf.split(iris.data, iris.target)):

    print("Fold：{}".format(fold),"len(train_index)：{}".format(len(train_index)), "len(test_index)：{}".format(len(test_index)))
    X_train = iris.data[train_index]
    X_test  = iris.data[test_index]
    y_train = iris.target[train_index]
    y_test  = iris.target[test_index]
```
**精度計算**


```
outputs = net(torch.tensor(X_test, dtype = torch.float))
_, y_predicted = torch.max(outputs.data, 1)
accuracy = 100 * np.sum(y_predicted.numpy() == y_test) / len(y_predicted)
print('accuracy: {:.1f}%'.format(accuracy))
```



In [2]:
# ライブラリのインポート
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np
from sklearn import datasets
from sklearn.model_selection import KFold


# ネットワークの定義
class IrisNet(nn.Module):

    def __init__(self):
        super(IrisNet, self).__init__()
        self.fc1 = nn.Linear(4, 12)
        self.fc2 = nn.Linear(12, 8)
        self.fc3 = nn.Linear(8, 3)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    
#  定数定義
FOLD = 3
IS_SHUFFLE = True
SEED = 1234
EPOCH = 5
LEARNING_LATE = 0.01

#  アイリスデータロード
iris = datasets.load_iris()

#  K分割交差検証
kf = KFold(n_splits=FOLD,shuffle=IS_SHUFFLE,random_state=SEED)

for fold,(train_index, test_index) in enumerate(kf.split(iris.data, iris.target)):
    
    print("Fold：{}".format(fold),"len(train_index)：{}".format(len(train_index)), "len(test_index)：{}".format(len(test_index)))
    X_train = iris.data[train_index]
    X_test  = iris.data[test_index]
    y_train = iris.target[train_index]
    y_test  = iris.target[test_index]
    
    x = torch.tensor(X_train,dtype = torch.float)
    y = torch.tensor(y_train)
    net = IrisNet()
    
    # optimezer定義
    optimizer = optim.SGD(net.parameters(), lr=LEARNING_LATE)
    
    # loss関数定義
    criterion = nn.CrossEntropyLoss()

    
    for i in range(EPOCH):
        # 勾配初期化
        optimizer.zero_grad()
        output = net(x)
        
        # loss算出
        loss = criterion(output, y)
        loss.backward()
        optimizer.step()
        print('epoch: {},'.format(i) + 'loss: {:.10f}'.format(loss))
        

    # 精度計算
    outputs = net(torch.tensor(X_test, dtype = torch.float))
    _, y_predicted = torch.max(outputs.data, 1)
    accuracy = 100 * np.sum(y_predicted.numpy() == y_test) / len(y_predicted)
    print('accuracy: {:.1f}%'.format(accuracy))

Fold：0 len(train_index)：100 len(test_index)：50
epoch: 0,loss: 1.0942015648
epoch: 1,loss: 1.0888361931
epoch: 2,loss: 1.0835262537
epoch: 3,loss: 1.0783267021
epoch: 4,loss: 1.0732574463
accuracy: 50.0%
Fold：1 len(train_index)：100 len(test_index)：50
epoch: 0,loss: 1.1317970753
epoch: 1,loss: 1.1304142475
epoch: 2,loss: 1.1290374994
epoch: 3,loss: 1.1276578903
epoch: 4,loss: 1.1262704134
accuracy: 24.0%
Fold：2 len(train_index)：100 len(test_index)：50
epoch: 0,loss: 1.1079429388
epoch: 1,loss: 1.1065307856
epoch: 2,loss: 1.1051388979
epoch: 3,loss: 1.1037675142
epoch: 4,loss: 1.1024180651
accuracy: 30.0%


### (9)学習済みモデルの保存

**モデルの実装**


```
import torch
torch.save(net.state_dict(), './XXXX.pth')
```



### (10)学習済みモデルのロード

**モデルのインスタンスの準備**


```
import torch.nn as nn
      
class IrisNet(nn.Module):
def __init__(self):
    super(IrisNet, self).__init__()
    self.fc1 = nn.Linear(4, 12)
    self.fc2 = nn.Linear(12, 8)
    self.fc3 = nn.Linear(8, 3)

def forward(self, x):
    x = F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    x = self.fc3(x)
    return x
        
loaded_mooel = IrisNet()
print(loaded_model)
```



**学習済みであるモデルの読み込み**


```
import torch.nn as nn
import torch

loaded_model.load_state_dict(torch.load('./iris_model_2fold_500epoch.pth', map_location=lambda storage, loc: storage), strict=True)
```



In [ ]:
# ライブラリのインポート
import torch
import torch.nn as nn

# IrisNetの定義
class IrisNet(nn.Module):
        
        def __init__(self):
            super(IrisNet, self).__init__()
            self.fc1 = nn.Linear(4, 12)
            self.fc2 = nn.Linear(12, 8)
            self.fc3 = nn.Linear(8, 3)

        def forward(self, x):
            x = F.relu(self.fc1(x))
            x = F.relu(self.fc2(x))
            x = self.fc3(x)
            return x

# モデルのインスタンス作成
loaded_model = IrisNet()

# 学習済みモデルのロード
loaded_model.load_state_dict(torch.load('./iris_model_2fold_500epoch.pth', map_location=lambda storage, loc: storage), strict=True)